export const countries = {
  "Bangladesh": "🇧🇩",
  "Brazil": "🇧🇷",
  "Indonesia": "🇮🇩",
  "Pakistan": "🇵🇰",
  "Philippines": "🇵🇭",
  "Russia": "🇷🇺",
  "Sri Lanka": "🇱🇰",
  "Tanzania": "🇹🇿",
  "Vietnam": "🇻🇳",
  "Argentina": "🇦🇷",
  "Bolivia": "🇧🇴",
  "Botswana": "🇧🇼",
  "Chile": "🇨🇱",
  "Nigeria": "🇳🇬",
  "Colombia": "🇨🇴",
  "Costa Rica": "🇨🇷",
  "DR Congo": "🇨🇩",
  "Kazakhstan": "🇰🇿",
  "Kenya": "🇰🇪",
  "Moldova": "🇲🇩",
  "Uganda": "🇺🇬",
  "Ukraine": "🇺🇦",
  "Uzbekistan": "🇺🇿",
  "Australia": "🇦🇺",
  "Spain": "🇪🇸",
  "United Kingdom": "🇬🇧",
  "Netherland": "🇳🇱",
  "Germany": "🇩🇪",
  "United Arab Emirates": "🇦🇪",
  "Saudi Arabia": "🇸🇦",
  "Oman": "🇴🇲",
  "Singapore": "🇸🇬",
  "Canada": "🇨🇦",
  "China": "🇨🇳",
  "USA": "🇺🇸",
  "Afghanistan": "🇦🇫",
  "Algeria": "🇩🇿",
  "Angola": "🇦🇴",
  "Armenia": "🇦🇲",
  "Austria": "🇦🇹",
  "Azerbaijan": "🇦🇿",
  "Bahrain": "🇧🇭",
  "Barbados": "🇧🇧",
  "Belgium": "🇧🇪",
  "Belarus": "🇧🇾",
  "Benin": "🇧🇯",
  "Bermuda": "🇧🇲",
  "Bhutan": "🇧🇹",
  "Bulgaria": "🇧🇬",
  "Burundi": "🇧🇮",
  "Cambodia": "🇰🇭",
  "Cameroon": "🇨🇲",
  "Chad": "🇹🇩",
  "Cote d ivoire": "🇨🇮",
  "Croatia": "🇭🇷",
  "Cyprus": "🇨🇾",
  "Czech Republic": "🇨🇿",
  "Denmark": "🇩🇰",
  "Dominican Republic": "🇩🇴",
  "Ecuador": "🇪🇨",
  "Egypt": "🇪🇬",
  "Estonia": "🇪🇪",
  "Ethiopia": "🇪🇹",
  "El Salvador": "🇸🇻",
  "Fiji": "🇫🇯",
  "Finland": "🇫🇮",
  "France": "🇫🇷",
  "Gabon": "🇬🇦",
  "Georgia": "🇬🇪",
  "Ghana": "🇬🇭",
  "Greece": "🇬🇷",
  "Guatemala": "🇬🇹",
  "Guinea": "🇬🇳",
  "Guyana": "🇬🇾",
  "Hungary": "🇭🇺",
  "Honduras": "🇭🇳",
  "Iran": "🇮🇷",
  "Iraq": "🇮🇶",
  "Ireland": "🇮🇪",
  "Israel": "🇮🇱",
  "Italy": "🇮🇹",
  "Jamaica": "🇯🇲",
  "Japan": "🇯🇵",
  "Jordan": "🇯🇴",
  "Kosovo": "🇽🇰",
  "Kuwait": "🇰🇼",
  "Kyrgyzstan": "🇰🇬",
  "Latvia": "🇱🇻",
  "Lesotho": "🇱🇸",
  "Liberia": "🇱🇷",
  "Libya": "🇱🇾",
  "Lithuania": "🇱🇹",
  "Luxembourg": "🇱🇺",
  "Malawi": "🇲🇼",
  "Malaysia": "🇲🇾",
  "Maldives": "🇲🇻",
  "Mauritius": "🇲🇺",
  "Morocco": "🇲🇦",
  "Mozambique": "🇲🇿",
  "Nepal": "🇳🇵",
  "New Zealand": "🇳🇿",
  "Nicaragua": "🇳🇮",
  "Niger": "🇳🇪",
  "Norway": "🇳🇴",
  "Namibia": "🇳🇦",
  "Palestine": "🇵🇸",
  "Panama": "🇵🇦",
  "Papua New Guinea": "🇵🇬",
  "Paraguay": "🇵🇾",
  "Peru": "🇵🇪",
  "Poland": "🇵🇱",
  "Portugal": "🇵🇹",
  "Qatar": "🇶🇦",
  "Romania": "🇷🇴",
  "Rwanda": "🇷🇼",
  "Sao Tome And Principe": "🇸🇹",
  "Senegal": "🇸🇳",
  "Serbia": "🇷🇸",
  "Seychelles": "🇸🇨",
  "Sierra Leone": "🇸🇱",
  "Slovakia": "🇸🇰",
  "Slovenia": "🇸🇮",
  "Somalia": "🇸🇴",
  "South Africa": "🇿🇦",
  "South Korea": "🇰🇷",
  "Sudan": "🇸🇩",
  "Sweden": "🇸🇪",
  "Switzerland": "🇨🇭",
  "Syria": "🇸🇾",
  "Taiwan": "🇹🇼",
  "Tajikistan": "🇹🇯",
  "Thailand": "🇹🇭",
  "Togo": "🇹🇬",
  "Trinidad And Tobago": "🇹🇹",
  "Tunisia": "🇹🇳",
  "Turkmenistan": "🇹🇲",
  "Uruguay": "🇺🇾",
  "Venezuela": "🇻🇪",
  "Yemen": "🇾🇪",
  "Zambia": "🇿🇲",
  "Zimbabwe": "🇿🇼"
};