export const countries = {
  Afghanistan: "https://flagcdn.com/w40/af.png",
  Algeria: "https://flagcdn.com/w40/al.png",
  Angola: "https://flagcdn.com/w40/an.png",
  Argentina: "https://flagcdn.com/w40/ar.png",
  Armenia: "https://flagcdn.com/w40/ar.png",
  Australia: "https://flagcdn.com/w40/au.png",
  Austria: "https://flagcdn.com/w40/au.png",
  Azerbaijan: "https://flagcdn.com/w40/az.png",
  Bahrain: "https://flagcdn.com/w40/ba.png",
  Bangladesh: "https://flagcdn.com/w40/ba.png",
  Barbados: "https://flagcdn.com/w40/ba.png",
  Belarus: "https://flagcdn.com/w40/be.png",
  Belgium: "https://flagcdn.com/w40/be.png",
  Benin: "https://flagcdn.com/w40/be.png",
  Bermuda: "https://flagcdn.com/w40/be.png",
  Bhutan: "https://flagcdn.com/w40/bh.png",
  Bolivia: "https://flagcdn.com/w40/bo.png",
  Botswana: "https://flagcdn.com/w40/bo.png",
  Brazil: "https://flagcdn.com/w40/br.png",
  Bulgaria: "https://flagcdn.com/w40/bu.png",
  Burundi: "https://flagcdn.com/w40/bu.png",
  Cambodia: "https://flagcdn.com/w40/ca.png",
  Cameroon: "https://flagcdn.com/w40/ca.png",
  Canada: "https://flagcdn.com/w40/ca.png",
  Chad: "https://flagcdn.com/w40/ch.png",
  Chile: "https://flagcdn.com/w40/ch.png",
  China: "https://flagcdn.com/w40/ch.png",
  Colombia: "https://flagcdn.com/w40/co.png",
  "Costa Rica": "https://flagcdn.com/w40/co.png",
  "Cote d'Ivoire": "https://flagcdn.com/w40/ci.png",
  Croatia: "https://flagcdn.com/w40/cr.png",
  Cyprus: "https://flagcdn.com/w40/cy.png",
  "Czech Republic": "https://flagcdn.com/w40/cz.png",
  Denmark: "https://flagcdn.com/w40/de.png",
  "Dominican Republic": "https://flagcdn.com/w40/do.png",
  "DR Congo": "https://flagcdn.com/w40/cd.png",
  Ecuador: "https://flagcdn.com/w40/ec.png",
  Egypt: "https://flagcdn.com/w40/eg.png",
  Estonia: "https://flagcdn.com/w40/es.png",
  Ethiopia: "https://flagcdn.com/w40/et.png",
  Fiji: "https://flagcdn.com/w40/fi.png",
  Finland: "https://flagcdn.com/w40/fi.png",
  France: "https://flagcdn.com/w40/fr.png",
  Gabon: "https://flagcdn.com/w40/ga.png",
  Georgia: "https://flagcdn.com/w40/ge.png",
  Germany: "https://flagcdn.com/w40/ge.png",
  Ghana: "https://flagcdn.com/w40/gh.png",
  Greece: "https://flagcdn.com/w40/gr.png",
  Guatemala: "https://flagcdn.com/w40/gu.png",
  Guinea: "https://flagcdn.com/w40/gu.png",
  Guyana: "https://flagcdn.com/w40/gu.png",
  Hungary: "https://flagcdn.com/w40/hu.png",
  India: "https://flagcdn.com/w40/in.png",
  Indonesia: "https://flagcdn.com/w40/in.png",
  Iran: "https://flagcdn.com/w40/ir.png",
  Iraq: "https://flagcdn.com/w40/ir.png",
  Ireland: "https://flagcdn.com/w40/ir.png",
  Israel: "https://flagcdn.com/w40/is.png",
  Italy: "https://flagcdn.com/w40/it.png",
  Jamaica: "https://flagcdn.com/w40/ja.png",
  Japan: "https://flagcdn.com/w40/ja.png",
  Jordan: "https://flagcdn.com/w40/jo.png",
  Kazakhstan: "https://flagcdn.com/w40/ka.png",
  Kenya: "https://flagcdn.com/w40/ke.png",
  Kosovo: "https://flagcdn.com/w40/ko.png",
  Kuwait: "https://flagcdn.com/w40/ku.png",
  Kyrgyzstan: "https://flagcdn.com/w40/ky.png",
  Latvia: "https://flagcdn.com/w40/la.png",
  Lesotho: "https://flagcdn.com/w40/le.png",
  Liberia: "https://flagcdn.com/w40/li.png",
  Libya: "https://flagcdn.com/w40/li.png",
  Lithuania: "https://flagcdn.com/w40/li.png",
  Luxembourg: "https://flagcdn.com/w40/lu.png",
  Malawi: "https://flagcdn.com/w40/ma.png",
  Malaysia: "https://flagcdn.com/w40/ma.png",
  Maldives: "https://flagcdn.com/w40/ma.png",
  Mauritius: "https://flagcdn.com/w40/ma.png",
  Mexico: "https://flagcdn.com/w40/me.png",
  Moldova: "https://flagcdn.com/w40/mo.png",
  Morocco: "https://flagcdn.com/w40/mo.png",
  Mozambique: "https://flagcdn.com/w40/mo.png",
  Nepal: "https://flagcdn.com/w40/ne.png",
  Netherlands: "https://flagcdn.com/w40/ne.png",
  "New Zealand": "https://flagcdn.com/w40/nz.png",
  Nicaragua: "https://flagcdn.com/w40/ni.png",
  Niger: "https://flagcdn.com/w40/ni.png",
  Nigeria: "https://flagcdn.com/w40/ni.png",
  Norway: "https://flagcdn.com/w40/no.png",
  Oman: "https://flagcdn.com/w40/om.png",
  Pakistan: "https://flagcdn.com/w40/pa.png",
  Palestine: "https://flagcdn.com/w40/pa.png",
  Panama: "https://flagcdn.com/w40/pa.png",
  "Papua New Guinea": "https://flagcdn.com/w40/pg.png",
  Paraguay: "https://flagcdn.com/w40/pa.png",
  Peru: "https://flagcdn.com/w40/pe.png",
  Philippines: "https://flagcdn.com/w40/ph.png",
  Poland: "https://flagcdn.com/w40/po.png",
  Portugal: "https://flagcdn.com/w40/po.png",
  Qatar: "https://flagcdn.com/w40/qa.png",
  Romania: "https://flagcdn.com/w40/ro.png",
  Russia: "https://flagcdn.com/w40/ru.png",
  Rwanda: "https://flagcdn.com/w40/rw.png",
  "Sao Tome and Principe": "https://flagcdn.com/w40/st.png",
  "Saudi Arabia": "https://flagcdn.com/w40/sa.png",
  Senegal: "https://flagcdn.com/w40/se.png",
  Serbia: "https://flagcdn.com/w40/se.png",
  Seychelles: "https://flagcdn.com/w40/se.png",
  "Sierra Leone": "https://flagcdn.com/w40/si.png",
  Singapore: "https://flagcdn.com/w40/si.png",
  Slovakia: "https://flagcdn.com/w40/sl.png",
  Slovenia: "https://flagcdn.com/w40/sl.png",
  Somalia: "https://flagcdn.com/w40/so.png",
  "South Africa": "https://flagcdn.com/w40/so.png",
  "South Korea": "https://flagcdn.com/w40/kr.png",
  Spain: "https://flagcdn.com/w40/sp.png",
  "Sri Lanka": "https://flagcdn.com/w40/sr.png",
  Sudan: "https://flagcdn.com/w40/su.png",
  Sweden: "https://flagcdn.com/w40/sw.png",
  Switzerland: "https://flagcdn.com/w40/sw.png",
  Syria: "https://flagcdn.com/w40/sy.png",
  Taiwan: "https://flagcdn.com/w40/ta.png",
  Tajikistan: "https://flagcdn.com/w40/ta.png",
  Tanzania: "https://flagcdn.com/w40/ta.png",
  Thailand: "https://flagcdn.com/w40/th.png",
  Togo: "https://flagcdn.com/w40/to.png",
  "Trinidad and Tobago": "https://flagcdn.com/w40/tt.png",
  Tunisia: "https://flagcdn.com/w40/tu.png",
  Turkey: "https://flagcdn.com/w40/tu.png",
  Turkmenistan: "https://flagcdn.com/w40/tu.png",
  Uganda: "https://flagcdn.com/w40/ug.png",
  Ukraine: "https://flagcdn.com/w40/uk.png",
  "United Arab Emirates": "https://flagcdn.com/w40/ae.png",
  "United Kingdom": "https://flagcdn.com/w40/gb.png",
  Uruguay: "https://flagcdn.com/w40/ur.png",
  USA: "https://flagcdn.com/w40/us.png",
  Uzbekistan: "https://flagcdn.com/w40/uz.png",
  Venezuela: "https://flagcdn.com/w40/ve.png",
  Vietnam: "https://flagcdn.com/w40/vi.png",
  Yemen: "https://flagcdn.com/w40/ye.png",
  Zambia: "https://flagcdn.com/w40/za.png",
  Zimbabwe: "https://flagcdn.com/w40/zi.png",
};
