import "./globals.css";
import Header from "./components/Header";
import Footer from './components/Footer'
import { Inter } from 'next/font/google';

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  display: 'swap',
  variable: '--font-inter',
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.variable}>
            <body className="font-sans">
                    <Header></Header>

              {children}
              <Footer></Footer>
              </body>

    </html>
  );
}
