import "./globals.css";
import Header from "./components/Header";
import Footer from './components/Footer'
import { Roboto } from "next/font/google";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // pick what you need
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={roboto.className}>
            <body className="font-sans">
                    <Header></Header>

              {children}
              <Footer></Footer>
              </body>

    </html>
  );
}
